# Generated by Django 5.0.4 on 2024-04-25 22:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("amicci", "0002_auto_20240425_1911"),
    ]

    operations = []
