# Generated by Django 5.0.4 on 2024-04-25 22:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("amicci", "0003_auto_20240425_1914"),
    ]

    operations = []
