# Generated by Django 5.0.4 on 2024-04-25 22:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("amicci", "0004_auto_20240425_1916"),
    ]

    operations = []
