# Generated by Django 5.0.4 on 2024-04-25 22:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("amicci", "0006_auto_20240425_1918"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Briefing",
        ),
        migrations.DeleteModel(
            name="Category",
        ),
        migrations.DeleteModel(
            name="Retailer",
        ),
        migrations.DeleteModel(
            name="Vendor",
        ),
    ]
