# Generated by Django 5.0.4 on 2024-04-25 22:37

from django.db import migrations, models
from django.contrib.postgres.fields import ArrayField

class Migration(migrations.Migration):
    dependencies = [
        ("amicci", "0007_delete_briefing_delete_category_delete_retailer_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name='Retailer',
            fields=[
                ('id', models.AutoField(primary_key=True)),
                ('name', models.CharField(max_length=100)),
                ('vendors', ArrayField(models.AutoField(), blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Briefing',
            fields=[
                ('id', models.AutoField(primary_key=True)),
                ('name', models.CharField(max_length=100)),
                ('retailer', models.CharField(max_length=200)),
                ('responsible', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=200)),
                ('release_date', models.CharField(max_length=50)),
                ('availabe', models.IntegerField())
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(primary_key=True)),
                ('name', models.CharField(max_length=100)),
            ],
        )
    ]
