# Generated by Django 5.0.4 on 2024-04-27 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("amicci", "0008_auto_20240425_1937"),
    ]

    operations = [
        migrations.AlterField(
            model_name="briefing",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="briefing",
            name="name",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="category",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="retailer",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="retailer",
            name="name",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="retailer",
            name="vendors",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="amicci.vendor"
            ),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="name",
            field=models.CharField(max_length=200),
        ),
    ]
