# Generated by Django 5.0.4 on 2024-04-27 13:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("amicci", "0009_alter_briefing_id_alter_briefing_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="retailer",
            name="vendors",
        ),
        migrations.AddField(
            model_name="retailer",
            name="vendors",
            field=models.ManyToManyField(to="amicci.vendor"),
        ),
    ]
