# Generated by Django 5.0.4 on 2024-04-27 15:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("amicci", "0010_remove_retailer_vendors_retailer_vendors"),
    ]

    operations = [
        migrations.AlterField(
            model_name="retailer",
            name="vendors",
            field=models.ManyToManyField(
                blank=True, related_name="retailers", to="amicci.vendor"
            ),
        ),
    ]
